### ISSUE TITLE
Failure Build

### ISSUE THREAD

**Issue by muzma** [openMF/message-gateway#10]
Can you help me, I have error when i run "./gradlew clean build -Pprofile=deployable". i don't know why because when i try to access "http://repo.spring.io/libs-release/com/mycila/xmltool/xmltool/3.3/" i can do it.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'message-gateway'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not download xmltool.jar (com.mycila.xmltool:xmltool:3.3)
      > Could not get resource 'http://repo.spring.io/libs-release/com/mycila/xmltool/xmltool/3.3/xmltool-3.3.jar'.
         > Could not HEAD 'http://repo.spring.io/libs-release/com/mycila/xmltool/xmltool/3.3/xmltool-3.3.jar'.
            > Connection reset

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by awasum** [comment]
Run it again, internet might be the problem.

**Comment by muzma** [comment]
Thanks @awasum , yes when i change internet sevice provider(isp) it's Done.

**Comment by awasum** [comment]
Close this issue please.
